# This is a basic workflow to help you get started with Actions
name: Testing envs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  define_env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "FOO1=bar1" >> $GITHUB_ENV

  testing:
    runs-on: ubuntu-latest
    needs: define_env
    steps:
      - run: export FOO2=bar2
      - run: echo "FOO3=bar3" >> $GITHUB_ENV
      - name: Print env vars in action
        run: |
          echo "FOO1=${{ env.FOO1 }}"
          echo "FOO2=${{ env.FOO2 }}"
          echo "FOO3=${{ env.FOO3 }}"
      - name: Print env vars available in process
        run: env
